#!/bin/bash
# Script for downloading all languages en masse.
#
# This does not exhaust the set of covered languages, merely those we have tried
# thus far.
#
# It seems that the MediaWiki backend may drop queries if too many are made at
# once; therefore we have to run this in serial.

set -eou pipefail

# TODO: Increment this from time to time.
readonly CUTOFFDATE="2019-08-01"

# Add these in alphabetic order with respect to their ISO-639-1 codes.

echo "Bulgarian..."
time wikipron "bg" \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=bg.tsv

echo "Czech..."
time wikipron cs \
    --phonetic \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=cs.tsv

echo "Danish..."
time wikipron da \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=da.tsv

echo "German..."
time wikipron de \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=de.tsv

echo "Greek..."
time wikipron el \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=el.tsv

echo "English (US)..."
time wikipron en \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --dialect="US | General American" \
    --cut-off-date="${CUTOFFDATE}" \
    --output=en.tsv

echo "Spanish (Latin America)..."
time wikipron es \
    --casefold \
    --no-stress \
    --dialect="Latin America" \
    --cut-off-date="${CUTOFFDATE}" \
    --output=es.tsv

echo "Estonian..."
time wikipron et \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=et.tsv

echo "Finnish..."
time wikipron "fi" \
    --phonetic \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=fi.tsv

echo "French (European)..."
time wikipron fr \
    --casefold \
    --no-syllable-boundaries \
    --dialect=European \
    --cut-off-date="${CUTOFFDATE}" \
    --output=fr.tsv

echo "Hindi..."
time wikipron hi \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=hi.tsv
    
echo "Hungarian..."
time wikipron hu \
    --phonetic \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=hu.tsv

echo "Italian..."
time wikipron it \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=it.tsv

# TODO: returns no pronunciations; unclear why.
#echo "Korean..."
#time wikipron ko \
#    --phonetic \
#    --no-syllable-boundaries \
#    --cut-off-date="${CUTOFFDATE}" \
#    --output=ko.tsv

echo "Lithuanian..."
time wikipron lt \
    --phonetic \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=lt.tsv

echo "Latvian..."
time wikipron lv \
    --phonetic \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=lv.tsv

echo "Dutch..."
time wikipron "nl" \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=nl.tsv

echo "Polish..."
time wikipron pl \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=pl.tsv

echo "Portuguese (European)..."
time wikipron pt \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --dialect="Portugal" \
    --cut-off-date="${CUTOFFDATE}" \
    --output=pt.tsv

echo "Romanian..."
time wikipron ro \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=ro.tsv

echo "Slovak..."
time wikipron sk \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=sk.tsv

echo "Slovene..."
time wikipron sl \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=sl.tsv

echo "Swedish..."
time wikipron sv \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=sv.tsv
